op {
  input: "LSTM1/seq_lengths"
  input: "LSTM1/i2h_w"
  input: "LSTM1/i2h_b"
  input: "LSTM1/gates_t_w"
  input: "LSTM1/gates_t_b"
  input: "LSTM1/hidden_init"
  input: "LSTM1/cell_init"
  input: "LSTM2/seq_lengths"
  input: "LSTM2/i2h_w"
  input: "LSTM2/i2h_b"
  input: "LSTM2/gates_t_w"
  input: "LSTM2/gates_t_b"
  input: "LSTM2/hidden_init"
  input: "LSTM2/cell_init"
  input: "fc1_w"
  input: "fc1_b"
  input: "fc2_w"
  input: "fc2_b"
  input: "iter"
  input: "LSTM1/i2h_w_moment_1"
  input: "LSTM1/i2h_w_moment_2"
  input: "LSTM1/i2h_b_moment_1"
  input: "LSTM1/i2h_b_moment_2"
  input: "LSTM1/hidden_init_moment_1"
  input: "LSTM1/hidden_init_moment_2"
  input: "LSTM1/cell_init_moment_1"
  input: "LSTM1/cell_init_moment_2"
  input: "LSTM1/gates_t_w_moment_1"
  input: "LSTM1/gates_t_w_moment_2"
  input: "LSTM1/gates_t_b_moment_1"
  input: "LSTM1/gates_t_b_moment_2"
  input: "LSTM2/i2h_w_moment_1"
  input: "LSTM2/i2h_w_moment_2"
  input: "LSTM2/i2h_b_moment_1"
  input: "LSTM2/i2h_b_moment_2"
  input: "LSTM2/hidden_init_moment_1"
  input: "LSTM2/hidden_init_moment_2"
  input: "LSTM2/cell_init_moment_1"
  input: "LSTM2/cell_init_moment_2"
  input: "LSTM2/gates_t_w_moment_1"
  input: "LSTM2/gates_t_w_moment_2"
  input: "LSTM2/gates_t_b_moment_1"
  input: "LSTM2/gates_t_b_moment_2"
  input: "fc1_w_moment_1"
  input: "fc1_w_moment_2"
  input: "fc1_b_moment_1"
  input: "fc1_b_moment_2"
  input: "fc2_w_moment_1"
  input: "fc2_w_moment_2"
  input: "fc2_b_moment_1"
  input: "fc2_b_moment_2"
  type: "Save"
  arg {
    name: "db_type"
    s: "lmdb"
  }
  arg {
    name: "db"
    s: "LSTM_params"
  }
}
